### ISSUE TITLE
Tidy data training feedback 

### ISSUE THREAD

**Issue by kbjarkefur** [dime-worldbank/dimeanalytics#19]

**Comment by kbjarkefur** [comment]
slide 11 - the long vs. wide example, is probable difficult to get. you said data is spread out on the row, and data is spread out over the columns

**Comment by kbjarkefur** [comment]
In the anthropology data, include the next column. It was not obvious to me that this was everything, but I think the columns to the right of this are empty, so could look like this was just the first few columns of a "normal" data set

**Comment by mariaruth** [comment]
correct slide 23

**Comment by kbjarkefur** [comment]
hh dataset - both gender variables are called gender_1

**Comment by kbjarkefur** [comment]
hh dataset, your main data has only up to 2 members, but the hh member data set had up to 5 members. This is one of those details that ppl new to this _could_ get stuck on. I think it is better to use the exact same data points shown in both tables. And maybe add arrows pointing

**Comment by kbjarkefur** [comment]
Maybe show an example on how much easier it is to do a tab or a summary of a nested variable in tidy data.

**Comment by kbjarkefur** [comment]
Show an example of how you save the tidy data. Will this be many files? and if so, what do you call all those files to indicate that they are all part of a single dataset

**Comment by kbjarkefur** [comment]
We didnt discuss how you go from tidy to the analysis set. That is not in the scope to show properly do that, but we need to give them an intuition for the workflow

**Comment by kbjarkefur** [comment]
Answer to Roshnis questions about data management. include how to keep track of the observations over the different data sets

**Comment by kbjarkefur** [comment]
tidy is important in data management, and then is when we need to be really strict about it. During data management we work on the unit of observation, i.e. the level we collect data on. during analysis, we should still keep data as tidy as possible, but we know work with unit of analysis, which could include data from other unit of observations. For example, an aggregation from a sub-observations (ex: sum of income from all plots), or some data merged to the unit of analysis from a super-observation (ex: merging school size to a student dataset)

**Comment by RRMaximiliano** [comment]
Differences between the level of analysis and level of observations (how to include this to the workflow of data cleaning and data analysis).

**Comment by luisesanmartin** [comment]
There was a comment (I think it was from Marc-Andrea) about graphs being a type of non-tabular data. I think he was referring to [this](https://en.wikipedia.org/wiki/Graph_(abstract_data_type)) rather than data visualizations

**Comment by kbjarkefur** [comment]
From discussion in end of call. 
* A tidy dataset should be saved as a folder with one or many files, where each file is a table. 
* We should know what the main unit of observation is in the tidy dataset. This unit should have a master dataset and be listed in the data linkage table, and this is how all the data in the tidy dataset is linked to all the other data in the project
* The data table with the main unit of observation should share the same name as the folder to clearly indicate which table is on the level of the main unit of observation.
* All other files in the folder represent other sub-unit of observation. These sub-units do not need to have a master dataset, but they very much could. The names of these sub-unit tables should be the same as the folder (and the main unit table) sub-scripted with an indication of the sub unit.

Example:

```
datasets/
  - baseline-hh-survey/
    - baseline-hh-survey.csv
    - baseline-hh-survey-hhmember.csv
    - baseline-hh-survey-plot.csv
```
