### ISSUE TITLE
AWS cloud onboarding

### ISSUE THREAD

**Issue by kbjarkefur** [dime-worldbank/dimeanalytics#26]
Leave feedback here - all slides are numbered in bottom right corner

**Comment by luizaandrade** [comment]
point 2.3 in slide 9 should talk about the C-account

**Comment by luizaandrade** [comment]
use US East-1 region

**Comment by luizaandrade** [comment]
the first time you access a server, it will prompt a security alert (slide 14)

**Comment by kbjarkefur** [comment]
All done in 910cb5462ad618db183f2543e5ac7e0b99064792
